---
id: 2024-12-07-keebkaigi2024-and_into_fewer_keys
base_name: and_into_fewer_keys
tags:
- CC-BY-4.0
presentation_date: '2024-12-07'
presentation_start_time:
presentation_end_time:
version: 2024.12.7.0
licenses: [CC-BY-4.0]
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1368
height: 768
source_code_uri: https://github.com/nishidayuya/rabbit-slide-nishidayuya-2024-12-07-keebkaigi2024-and_into_fewer_keys
author:
  markup_language: :markdown
  name: Yuya.Nishida.
  email:
  rubygems_user: nishidayuya
  slideshare_user:
  speaker_deck_user: nishidayuya
